src/components/header/edit_user/index.jsx
src/components/header/index.jsx
src/components/header/show_user/index.jsx
src/components/header/side_bar/index.jsx
src/components/header/styles.js

Foi resolvido o bug de não fechar a div Sidebar quando é clicado fora da mesma também foi adicionado função para redirecionar para home quando é clicado na logo do header

Fix: Resolvido click fora do sidebar não fechava div

---

src/components/home_components/Carousel/styles.js

Fix da responsividade do caroussel.

fix: arrumado a responsividade do caroussel

---

src/pages/lobby/index.jsx
src/pages/lobby/styles.js

Style: backgorund do Lobby;
Chore: Compoente Header na pagina de Lobby;
Chore: Compoente ModalInboxx na pagina de Lobby.

Fix: background do Lobby, inclusao do Header e Chat

---

src/components/lobby_components/UsersList/Card/index.jsx
src/components/lobby_components/UsersList/Card/styles.js
src/components/modal_inbox/styles.js

Feito a integração do talkjs com o usuário da internal api

Feat: adicionado integração da api modal chat

---

src/components/lobby_components/UsersList/Card/index.jsx
src/components/modal_inbox/index.jsx

Foi alterado o display para none do svg quando o iframe da mensagem é carregado.

Fix: Alterado quando é mostrado o loading icon

---

src/components/header/show_user/index.jsx

Div bio estava duplicada, vou resolvido o erro

Fix: Div bio estava duplicada, corrigido

---

.vscode/settings.json
src/components/header/show_user/index.jsx
src/components/login_components/FormLogin/index.jsx

Mensagem de sucesso ao logar nao esta mais aparecendo na Home;
Quando nao tiver nenhuma plataforma cadastrada, sera visualizada a Div de "Nenhuma plataforma cadastrada".

Fix: toast de login e condicao de plataformas cadastradas

---

src/components/header/side_bar/index.jsx
src/components/lobby_components/user_status/index.jsx

Resolvido erro ao adicionar e remover status não estava aparecendo na sidebar

Fix: resolvido bug de não atualizar o sidebar

---

src/components/lobby_components/UsersList/Card/styles.js

Ajustado altura do background color do modal chat

Fix: Ajustado background escuro do modal chat

---

src/style/globalStyle.js

Alterado o background em todos os navegadores

Fix: ajustado cores do progress bar

---

src/components/login_components/BackgroundLogo/style.js
src/components/login_components/DivLogo/style.js
src/components/login_components/FormLogin/index.jsx
src/components/login_components/FormLogin/style.js
src/components/register_components/BackgroundLogo/style.js
src/components/register_components/DivLogo/style.js
src/components/register_components/FormRegister/index.jsx
src/components/register_components/FormRegister/style.js

Ajustado responsividade do form login e register e background color

Fix: Ajustado responsividade do form login/register

---

src/components/header/side_bar/index.jsx
src/components/login_components/FormLogin/index.jsx
src/pages/lobby/index.jsx

Realizado ajustes no modal de login e logout

Fix: ajustado modal do login e logout

---

src/components/header/index.jsx
src/components/header/side_bar/index.jsx
src/components/lobby_components/UsersList/Card/styles.js
src/pages/home/index.jsx

Resolvido erros de duplicidade do modal de setar status, resolvido erro de modal não aparecer ao editar usuário

Fix: Ajustado modal editUser/removeStatus/Lobby

---

src/components/lobby_components/user_status/index.jsx

Realizado alterações na requisição de status na API

Fix: Erro na requisição de update/create status

---

src/components/header/side_bar/index.jsx

Foi altererado o localstorage ao dar logout de remove para clear

Fix: alterado de remove para clear ao dar logout

---

src/components/header/index.jsx

Foi alterado como é fechado a div do sidebar

Fix: resolvido bug do click menu sidebar

---

src/components/lobby_components/UsersList/Card/index.jsx
src/components/lobby_components/UsersList/Card/styles.js
src/components/lobby_components/UsersList/feedback/feedbackModal/Feedback/index.jsx
src/components/lobby_components/UsersList/feedback/feedbackModal/Played/index.jsx
src/components/lobby_components/UsersList/index.jsx
src/context/currentLobby/index.js

logica do feedback finalizado, tudo ok e testado.

feedback finalizado

---

src/components/header/index.jsx
src/components/header/side_bar/index.jsx

Arrumado bug no qual não aparecia modal de sucesso de remover status na home

Fix: ajustado modal de remover status na home

---

src/components/lobby_components/UsersList/feedback/feedbackModal/Feedback/index.jsx

Adicionado modal de sucesso ao enviar feeedback

Fix: adicionado modal de sucesso feedback

---

src/components/login_components/FormLogin/index.jsx
src/pages/lobby/index.jsx
src/pages/login/index.jsx

usuário não consegue acessar a home se não estiver logado

Fix: ajustado proteção de rotas

---

src/components/header/index.jsx
src/pages/lobby/index.jsx

Arrumado bug de duplicidade do modal de sucesso na lobby

Fix: Modal de sucesso no lobby duplicado
